version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - my-network

  grafana:
    image: grafana/grafana:11.1.3
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=redis-datasource
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  grafana-storage:
